spring:
  main:
    allow-bean-definition-overriding: true
  profiles.active: local
  # 데이터 소스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 작성 필요
    url: jdbc:mysql://localhost:3306/dream_of_refrigerator
    username: root
    password: wogml0517!
  # JPA 설정
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: 100
        jdbc.batch_size: 1000
        order_inserts: true
        order_updates: true
        format_sql: true