--가공/유제품 category
INSERT INTO ingredient(name,category)VALUES('계란','가공/유제품');
INSERT INTO ingredient(name,category)VALUES('모짜렐라치즈','가공/유제품');
INSERT INTO ingredient(name,category)VALUES('버터','가공/유제품');
INSERT INTO ingredient(name,category)VALUES('요거트','가공/유제품');
INSERT INTO ingredient(name,category)VALUES('체다치즈','가공/유제품');
INSERT INTO ingredient(name,category)VALUES('통조림참치','가공/유제품');
INSERT INTO ingredient(name,category)VALUES('통조림옥수수','가공/유제품');
INSERT INTO ingredient(name,category)VALUES('우유','가공/유제품');
INSERT INTO ingredient(name,category)VALUES('라이스페이퍼','가공/유제품');
-- 고기 category
INSERT INTO ingredient(name,category)VALUES('우삼겹','고기');
INSERT INTO ingredient(name,category)VALUES('훈제오리','고기');
INSERT INTO ingredient(name,category)VALUES('대패삼겹살','고기');
INSERT INTO ingredient(name,category)VALUES('비엔나소세지','고기');
INSERT INTO ingredient(name,category)VALUES('베이컨','고기');
INSERT INTO ingredient(name,category)VALUES('삼겹살','고기');
INSERT INTO ingredient(name,category)VALUES('차돌박이','고기');
INSERT INTO ingredient(name,category)VALUES('닭가슴살','고기');